#41 More filters for finding participants
kblincoe/QualOpt_SE701 pull request #150
Opened 2018-03-28 04:24 UTC by oliver-allen

This pull request closes #41 

There are 3 new properties to filter a participant by:
- Name
- Number of followers
- Number of following

The Participant class now has these properties as fields and can be created through the GitHub API and manually creating a participant.

The Participant page includes extra fields for filtering participants by these properties. They are also reflected in the table of participants
![screen shot 2018-03-28 at 5 14 02 pm](https://user-images.githubusercontent.com/20413754/38008590-0bc7ee02-32ac-11e8-803f-3de8e1e06ba5.png)

The viewing and editing pages of Participants also reflect these new properties
![screen shot 2018-03-28 at 5 20 08 pm](https://user-images.githubusercontent.com/20413754/38008680-7b47ea7a-32ac-11e8-9db7-903369cc35bb.png) ![screen shot 2018-03-28 at 5 20 24 pm](https://user-images.githubusercontent.com/20413754/38008679-7b152252-32ac-11e8-88ed-9fecc6a3595f.png)

2018-03-28 04:31 UTC, oliver-allen commented
This will effects some of the open issues:

#34 Link filtering participants to studies
#136 Adding unit tests for GitHubResource REST controller and refactoring for Testability
#149 Bug: Only allow positive numeric values of a participant

2018-03-28 04:52 UTC, xavier630 approved these changes
Nice one! We did the review together at your computer.

2018-03-28 06:21 UTC, JoeHorvath requested changes
In Participant.json it looks like you put 'followers' in twice. Was one of them meant to be 'following'?

2018-03-28 06:22 UTC, JoeHorvath commented on .jhipster/Participant.json
> +            "fieldName": "followers",
Should be "following"

2018-03-28 06:59 UTC, oliver-allen commented
Good splotting. It seems to work even with that error. Fixed and tested.

2018-03-28 07:06 UTC, JoeHorvath approved these changes
Nice work. Remember to squash your commits!

2018-03-29 00:27 UTC, oliver-allen commented
@softeng-701 Ready to merge. It has been reviewed and squashed as much as I can

2022-07-24 03:02 UTC, closed without merging